version: "3.9"
services:
  # corex
  icrep:
    image: torresmateo/icrep:dev
    # build: 
    #   context: ./icrepweb
    #   dockerfile: Dockerfile.prod
    command: gunicorn icrepweb.wsgi:application --bind 0.0.0.0:80 -w 4
    volumes:
      - static_icrep:/home/app/icrep/staticfiles
      - ./icrepweb/base:/home/app/icrep/base
      - ./icrepweb/icrepweb:/home/app/icrep/icrepweb
    # uncomment these to access the app directly for test purposes, 
    # but expect everything to be broken.
    ports:
      - 8080:80
    env_file: 
      - ./.env.icrep.prod
    networks:
      - icrep
    depends_on:
      icrep-db:
        condition: service_healthy
  icrep-db:
    image: postgres:13.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10 # this might seem too many retries, but there is data being copied...
    volumes:
      - icrep-db_data:/var/lib/postgresql/data/
      - ./icrep.dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.icrep.prod.db
    networks:
      - icrep
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - icrep
  # reverse proxy
  proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/nginx.conf
        #- static_icrep:/home/app/icrep/staticfiles
      - ./icrepweb/base/static:/home/app/icrep/staticfiles
    networks:
      - icrep
    ports:
      - 80:80
    depends_on:
      - icrep
networks:
  icrep:
    name: icrep
    external: false

volumes:
  icrep-db_data:
  static_icrep:
