version: "3.9"
services:
  # corex
  proteoboost:
    build: 
      context: ./proteoboostweb
      dockerfile: Dockerfile.prod
    command: gunicorn proteoboostweb.wsgi:application --bind 0.0.0.0:80 -w 4
    volumes:
      - static_proteoboost:/home/app/proteoboost/staticfiles
    env_file: 
      - ./.env.proteoboost.prod
    networks:
      - proteoboost
    depends_on:
      proteoboost-db:
        condition: service_healthy
  proteoboost-db:
    image: postgres:13.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10 # this might seem too many retries, but there is data being copied...
    volumes:
      - proteoboost-db_data:/var/lib/postgresql/data/
      - ./databases/proteoboost.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.proteoboost.prod.db
    networks:
      - proteoboost

  # reverse proxy
  proxy:
    build: ./reverse-proxy
    volumes:
      - static_proteoboost:/home/app/proteoboost/staticfiles
    networks:
      - proteoboost
    ports:
      - 80:80
    depends_on:
      - proteoboost
networks:
  proteoboost:
    name: proteoboost
    external: false

volumes:
  proteoboost-db_data:
  static_proteoboost:
