version: "3.9"
services:
  # corex
  proteobooster:
    #image: torresmateo/proteobooster:dev
    build: 
      context: ./proteobooster
      dockerfile: Dockerfile.prod
    command: gunicorn proteoboosterweb.wsgi:application --bind 0.0.0.0:80 -w 4
    volumes:
      #- static_proteobooster:/home/app/proteobooster/staticfiles
      - ./proteobooster/base/static:/home/app/proteobooster/staticfiles
      - ./proteobooster/base:/home/app/proteobooster/base
      - ./proteobooster/proteoboosterweb:/home/app/proteobooster/proteoboosterweb
    # uncomment these to access the app directly for test purposes, 
    # but expect everything to be broken.
    ports:
      - 8080:80
    env_file: 
      - ./.env.proteobooster.dev
    networks:
      - proteobooster
    depends_on:
      proteobooster-db:
        condition: service_healthy
  proteobooster-db:
    image: postgres:13.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10 # this might seem too many retries, but there is data being copied...
    volumes:
      - proteobooster-db_data:/var/lib/postgresql/data/
      - ./proteobooster.dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.proteobooster.dev.db
    networks:
      - proteobooster
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - proteobooster
  # reverse proxy
  proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/nginx.conf
        #- static_proteobooster:/home/app/proteobooster/staticfiles
      - ./proteobooster/base/static:/home/app/proteobooster/staticfiles
    networks:
      - proteobooster
    ports:
      - 80:80
    depends_on:
      - proteobooster
networks:
  proteobooster:
    name: proteobooster
    external: false

volumes:
  proteobooster-db_data:
  static_proteobooster:
