version: "3.9"
services:
  # corex
  proteobooster:
    build: 
      context: ./proteoboosterweb
      dockerfile: Dockerfile.prod
    command: gunicorn proteoboosterweb.wsgi:application --bind 0.0.0.0:80 -w 4
    volumes:
      - static_proteobooster:/home/app/proteobooster/staticfiles
    env_file: 
      - ./.env.proteobooster.prod
    networks:
      - proteobooster
    depends_on:
      proteobooster-db:
        condition: service_healthy
  proteobooster-db:
    image: postgres:13.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10 # this might seem too many retries, but there is data being copied...
    volumes:
      - proteobooster-db_data:/var/lib/postgresql/data/
      - ./databases/proteobooster.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.proteobooster.prod.db
    networks:
      - proteobooster

  # reverse proxy
  proxy:
    build: ./reverse-proxy
    volumes:
      - static_proteobooster:/home/app/proteobooster/staticfiles
    networks:
      - proteobooster
    ports:
      - 80:80
    depends_on:
      - proteobooster
networks:
  proteobooster:
    name: proteobooster
    external: false

volumes:
  proteobooster-db_data:
  static_proteobooster:
